name: push-master
on:
  push:
    branches:
    - master
jobs:
  mods-1_7_10:
    name: mods-1.7.10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: cristalix-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-mods-1_7_10

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Prepare Forge workspace
      run: ./gradlew setupDecompWorkspace

    - name: Build with Gradle
      run: ./gradlew mods-1.7.10:build


    - name: 'Deploy to Cristalix #3 DivinePVP-1'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CRISTALIX_3_HOST }}
        username: ${{ secrets.CRISTALIX_3_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/mods-1.7.10/server-cristalix-mods-1.3.3.7.jar
        target: /home/divinepvp-1/mods/1.7.10
        strip_components: 2

    - name: 'Deploy to Cristalix #3 DivinePVP-2'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CRISTALIX_3_HOST }}
        username: ${{ secrets.CRISTALIX_3_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/mods-1.7.10/server-cristalix-mods-1.3.3.7.jar
        target: /home/divinepvp-2/mods/1.7.10
        strip_components: 2

    - name: 'Deploy to Cristalix #3 SkyVoid-1'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CRISTALIX_3_HOST }}
        username: ${{ secrets.CRISTALIX_3_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/mods-1.7.10/server-cristalix-mods-1.3.3.7.jar
        target: /home/skyvoid-1/mods/1.7.10
        strip_components: 2

    - name: 'Deploy to Cristalix #3 MineZ-1'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CRISTALIX_3_HOST }}
        username: ${{ secrets.CRISTALIX_3_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/mods-1.7.10/server-cristalix-mods-1.3.3.7.jar
        target: /home/minez-1/mods/1.7.10
        strip_components: 2

    - name: 'Deploy to Cristalix #3 MineZ-Test'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CRISTALIX_3_HOST }}
        username: ${{ secrets.CRISTALIX_3_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/mods-1.7.10/server-cristalix-mods-1.3.3.7.jar
        target: /home/minez-test/mods/1.7.10
        strip_components: 2

    - name: 'Deploy to Cristalix #3 NeoTech-1'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CRISTALIX_3_HOST }}
        username: ${{ secrets.CRISTALIX_3_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/mods-1.7.10/server-cristalix-mods-1.3.3.7.jar
        target: /home/neotech-1/mods/1.7.10
        strip_components: 2

    - name: 'Deploy to Cristalix #3 Magica-1'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CRISTALIX_3_HOST }}
        username: ${{ secrets.CRISTALIX_3_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/mods-1.7.10/server-cristalix-mods-1.3.3.7.jar
        target: /home/magica-1/mods/1.7.10
        strip_components: 2

    - name: 'Deploy to Cristalix #3 TechnoMagic-1'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CRISTALIX_3_HOST }}
        username: ${{ secrets.CRISTALIX_3_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/mods-1.7.10/server-cristalix-mods-1.3.3.7.jar
        target: /home/technomagic-1/mods/1.7.10
        strip_components: 2

    - name: 'Deploy to Cristalix #3 TechnoMagic-2'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CRISTALIX_3_HOST }}
        username: ${{ secrets.CRISTALIX_3_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/mods-1.7.10/server-cristalix-mods-1.3.3.7.jar
        target: /home/technomagic-2/mods/1.7.10
        strip_components: 2


    - name: 'Deploy to LaunchServer DivinePVP'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LAUNCHSERVER_HOST }}
        username: ${{ secrets.LAUNCHSERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/mods-1.7.10/client-cristalix-mods-1.3.3.7.jar
        target: /home/certainlach/docker/launchserver-new/testUpdates/DivinePVP/mods/1.7.10
        strip_components: 2

    - name: 'Deploy to LaunchServer SkyVoid'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LAUNCHSERVER_HOST }}
        username: ${{ secrets.LAUNCHSERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/mods-1.7.10/client-cristalix-mods-1.3.3.7.jar
        target: /home/certainlach/docker/launchserver-new/testUpdates/SkyVoid/mods/1.7.10
        strip_components: 2

    - name: 'Deploy to LaunchServer MineZ'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LAUNCHSERVER_HOST }}
        username: ${{ secrets.LAUNCHSERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/mods-1.7.10/client-cristalix-mods-1.3.3.7.jar
        target: /home/certainlach/docker/launchserver-new/testUpdates/MineZ/mods/1.7.10
        strip_components: 2

    - name: 'Deploy to LaunchServer MineZ-Test'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LAUNCHSERVER_HOST }}
        username: ${{ secrets.LAUNCHSERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/mods-1.7.10/client-cristalix-mods-1.3.3.7.jar
        target: /home/certainlach/docker/launchserver-new/testUpdates/MineZ-Test/mods/1.7.10
        strip_components: 2

    - name: 'Deploy to LaunchServer NeoTech'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LAUNCHSERVER_HOST }}
        username: ${{ secrets.LAUNCHSERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/mods-1.7.10/client-cristalix-mods-1.3.3.7.jar
        target: /home/certainlach/docker/launchserver-new/testUpdates/NeoTech/mods/1.7.10
        strip_components: 2

    - name: 'Deploy to LaunchServer Magica'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LAUNCHSERVER_HOST }}
        username: ${{ secrets.LAUNCHSERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/mods-1.7.10/client-cristalix-mods-1.3.3.7.jar
        target: /home/certainlach/docker/launchserver-new/testUpdates/Magica/mods/1.7.10
        strip_components: 2

    - name: 'Deploy to LaunchServer TechnoMagic'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LAUNCHSERVER_HOST }}
        username: ${{ secrets.LAUNCHSERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/mods-1.7.10/client-cristalix-mods-1.3.3.7.jar
        target: /home/certainlach/docker/launchserver-new/testUpdates/TechnoMagic/mods/1.7.10
        strip_components: 2

    - name: 'Restart test LaunchServer'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LAUNCHSERVER_HOST }}
        username: ${{ secrets.LAUNCHSERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: ./dockerRestart

  skyblock-bukkit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: cristalix-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-skyblock-bukkit

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew skyblock-bukkit:build

    - name: 'Deploy to Cristalix #3'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CRISTALIX_3_HOST }}
        username: ${{ secrets.CRISTALIX_3_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/skyblock-bukkit/cristalix-skyblock-1.3.3.7.jar
        target: /home/skyvoid-1/plugins
        strip_components: 2

  server-wrapper:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: cristalix-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-server-wrapper

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew server-wrapper:build

    - name: 'Deploy to Cristalix #3'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CRISTALIX_3_HOST }}
        username: ${{ secrets.CRISTALIX_3_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/server-wrapper/server-wrapper-1.3.3.7.jar
        target: /home/util
        strip_components: 2

  plugins-bukkit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-plugins-bukkit

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew plugins-bukkit:build

    - name: 'Deploy to Cristalix #3'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CRISTALIX_3_HOST }}
        username: ${{ secrets.CRISTALIX_3_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/plugins-bukkit/cristalix-plugins-1.3.3.7.jar
        target: /home/plugins
        strip_components: 2