name: push-dev
on:
  push:
    branches:
    - dev
jobs:
  mods-1_7_10:
    name: mods-1.7.10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: cristalix-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-mods-1_7_10

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Prepare Forge workspace
      run: ./gradlew setupDecompWorkspace

    - name: Build with Gradle
      run: ./gradlew mods-1.7.10:build


    - name: 'Deploy to Cristalix #3 Thermos-Test'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CRISTALIX_3_HOST }}
        username: ${{ secrets.CRISTALIX_3_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/mods-1.7.10/server-cristalix-mods-1.3.3.7.jar
        target: /home/thermos-test/mods/1.7.10
        strip_components: 2

  skyblock-bukkit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: cristalix-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-skyblock-bukkit

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew skyblock-bukkit:build

  server-wrapper:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: cristalix-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-server-wrapper

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew server-wrapper:build

    - name: 'Deploy to Cristalix #3 Thermos-Test'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CRISTALIX_3_HOST }}
        username: ${{ secrets.CRISTALIX_3_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/server-wrapper/server-wrapper-1.3.3.7.jar
        target: /home/thermos-test
        strip_components: 2

  plugins-bukkit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-plugins-bukkit

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew plugins-bukkit:build

    - name: 'Deploy to Cristalix #3 Thermos-Test'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CRISTALIX_3_HOST }}
        username: ${{ secrets.CRISTALIX_3_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: output/plugins-bukkit/cristalix-plugins-1.3.3.7.jar
        target: /home/thermos-test/plugins
        strip_components: 2